language: python
# cache:
#   directories:
#   - "$HOME/google-cloud-sdk/"
env:
- PATH=$PATH:${HOME}/google-cloud-sdk/bin
before_install:
- ls
# - openssl aes-256-cbc -K $encrypted_96e26628a713_key -iv $encrypted_96e26628a713_iv
#   -in credentials.tar.gz.enc -out credentials.tar.gz -d
- curl https://sdk.cloud.google.com | bash;
- tar -xzf credentials.tar.gz
- mkdir -p lib
# Here we use the decrypted service account credentials to authenticate the command line tool
- gcloud auth activate-service-account --key-file client-secret.json
# [END auth]
