language: python
env:
- PATH=$PATH:${HOME}/google-cloud-sdk/bin
before_install:
- openssl aes-256-cbc -K $encrypted_1755f07573ab_key -iv $encrypted_1755f07573ab_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- ls
- curl https://sdk.cloud.google.com | bash;
- tar -xzf credentials.tar.gz
- mkdir -p lib
- gcloud auth activate-service-account --key-file client-secret.json
